[package]
name = "gpustat4cluster-client-backend"
version = "0.1.1"
edition = "2021"

[features]
default = []

[[bin]]
name = "gpustat4cluster-client-backend"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
toml = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
socket2 = "0.6"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
